// ข้อมูลทีมฟุตบอลครบทุกลีกดัง (Big 5 Leagues) - 96 ทีม
const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://classic-e8ab7-default-rtdb.asia-southeast1.firebasedatabase.app"
});

const db = admin.firestore();

const leagues = [
  { id: "premier-league", name: "Premier League", thaiName: "พรีเมียร์ลีก", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Premier_League_Logo.svg/1200px-Premier_League_Logo.svg.png", country: "England", order: 1 },
  { id: "laliga", name: "La Liga", thaiName: "ลาลีกา", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/LaLiga_logo_2023.svg/1200px-LaLiga_logo_2023.svg.png", country: "Spain", order: 2 },
  { id: "serie-a", name: "Serie A", thaiName: "กัลโช่ เซเรีย อา", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Serie_A_logo_2022.svg/1200px-Serie_A_logo_2022.svg.png", country: "Italy", order: 3 },
  { id: "bundesliga", name: "Bundesliga", thaiName: "บุนเดสลีกา", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Bundesliga_logo_%282017%29.svg/1200px-Bundesliga_logo_%282017%29.svg.png", country: "Germany", order: 4 },
  { id: "ligue-1", name: "Ligue 1", thaiName: "ลีกเอิง", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Ligue_1_Uber_Eats.svg/1200px-Ligue_1_Uber_Eats.svg.png", country: "France", order: 5 }
];

const teams = [
  // Premier League (20)
  { id: "manchester-united", leagueId: "premier-league", name: "Manchester United", thaiName: "แมนเชสเตอร์ ยูไนเต็ด", shortName: "MUN", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png", colors: { primary: "#DA291C", secondary: "#000000" }, gradient: "from-red-600 to-black", textGlow: "text-red-500" },
  { id: "manchester-city", leagueId: "premier-league", name: "Manchester City", thaiName: "แมนเชสเตอร์ ซิตี้", shortName: "MCI", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png", colors: { primary: "#6CABDD", secondary: "#FFFFFF" }, gradient: "from-blue-400 to-blue-700", textGlow: "text-blue-400" },
  { id: "liverpool", leagueId: "premier-league", name: "Liverpool", thaiName: "ลิเวอร์พูล", shortName: "LIV", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png", colors: { primary: "#C8102E", secondary: "#00B2A9" }, gradient: "from-red-600 to-red-900", textGlow: "text-red-500" },
  { id: "arsenal", leagueId: "premier-league", name: "Arsenal", thaiName: "อาร์เซนอล", shortName: "ARS", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png", colors: { primary: "#EF0107", secondary: "#FFFFFF" }, gradient: "from-red-500 to-red-800", textGlow: "text-red-400" },
  { id: "chelsea", leagueId: "premier-league", name: "Chelsea", thaiName: "เชลซี", shortName: "CHE", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png", colors: { primary: "#034694", secondary: "#FFFFFF" }, gradient: "from-blue-700 to-blue-900", textGlow: "text-blue-500" },
  { id: "tottenham", leagueId: "premier-league", name: "Tottenham Hotspur", thaiName: "ท็อตแน่ม ฮ็อทสเปอร์", shortName: "TOT", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/1200px-Tottenham_Hotspur.svg.png", colors: { primary: "#FFFFFF", secondary: "#132257" }, gradient: "from-gray-100 to-gray-400", textGlow: "text-white" },
  { id: "newcastle", leagueId: "premier-league", name: "Newcastle United", thaiName: "นิวคาสเซิ่ล ยูไนเต็ด", shortName: "NEW", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/1200px-Newcastle_United_Logo.svg.png", colors: { primary: "#241F20", secondary: "#F0B83D" }, gradient: "from-black to-yellow-400", textGlow: "text-yellow-400" },
  { id: "aston-villa", leagueId: "premier-league", name: "Aston Villa", thaiName: "แอสตัน วิลล่า", shortName: "AVL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Aston_Villa_FC_crest_%282016%29.svg/1200px-Aston_Villa_FC_crest_%282016%29.svg.png", colors: { primary: "#95BFE5", secondary: "#670E36" }, gradient: "from-red-700 to-blue-300", textGlow: "text-blue-300" },
  { id: "brighton", leagueId: "premier-league", name: "Brighton & Hove Albion", thaiName: "ไบรท์ตัน", shortName: "BHA", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/1200px-Brighton_%26_Hove_Albion_logo.svg.png", colors: { primary: "#0057B8", secondary: "#FFFFFF" }, gradient: "from-blue-600 to-yellow-300", textGlow: "text-blue-400" },
  { id: "west-ham", leagueId: "premier-league", name: "West Ham United", thaiName: "เวสต์แฮม ยูไนเต็ด", shortName: "WHU", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/1200px-West_Ham_United_FC_logo.svg.png", colors: { primary: "#7A263A", secondary: "#1BB1E7" }, gradient: "from-red-800 to-blue-400", textGlow: "text-blue-400" },
  { id: "crystal-palace", leagueId: "premier-league", name: "Crystal Palace", thaiName: "คริสตัล พาเลซ", shortName: "CRY", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Crystal_Palace_FC_logo_%282022%29.svg/1200px-Crystal_Palace_FC_logo_%282022%29.svg.png", colors: { primary: "#1B458F", secondary: "#C4122E" }, gradient: "from-blue-700 to-red-500", textGlow: "text-blue-400" },
  { id: "brentford", leagueId: "premier-league", name: "Brentford", thaiName: "เบรนท์ฟอร์ด", shortName: "BRE", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/1200px-Brentford_FC_crest.svg.png", colors: { primary: "#E30613", secondary: "#FFFFFF" }, gradient: "from-red-500 to-white", textGlow: "text-red-400" },
  { id: "fulham", leagueId: "premier-league", name: "Fulham", thaiName: "ฟูแล่ม", shortName: "FUL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Fulham_FC_%28shield%29.svg/1200px-Fulham_FC_%28shield%29.svg.png", colors: { primary: "#FFFFFF", secondary: "#000000" }, gradient: "from-white to-black", textGlow: "text-white" },
  { id: "everton", leagueId: "premier-league", name: "Everton", thaiName: "เอฟเวอร์ตัน", shortName: "EVE", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/1200px-Everton_FC_logo.svg.png", colors: { primary: "#003399", secondary: "#FFFFFF" }, gradient: "from-blue-700 to-blue-900", textGlow: "text-blue-400" },
  { id: "nottingham-forest", leagueId: "premier-league", name: "Nottingham Forest", thaiName: "นอตติ้งแฮม ฟอเรสต์", shortName: "NFO", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Nottingham_Forest_F.C._logo.svg/1200px-Nottingham_Forest_F.C._logo.svg.png", colors: { primary: "#DD0000", secondary: "#FFFFFF" }, gradient: "from-red-600 to-red-800", textGlow: "text-red-500" },
  { id: "bournemouth", leagueId: "premier-league", name: "AFC Bournemouth", thaiName: "บอร์นมัธ", shortName: "BOU", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5f/AFC_Bournemouth_%282013%29.svg/1200px-AFC_Bournemouth_%282013%29.svg.png", colors: { primary: "#DA291C", secondary: "#000000" }, gradient: "from-red-500 to-black", textGlow: "text-red-400" },
  { id: "wolves", leagueId: "premier-league", name: "Wolverhampton Wanderers", thaiName: "วูล์ฟแฮมป์ตัน", shortName: "WOL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Wolverhampton_Wanderers.svg/1200px-Wolverhampton_Wanderers.svg.png", colors: { primary: "#FDB913", secondary: "#231F20" }, gradient: "from-yellow-400 to-black", textGlow: "text-yellow-400" },
  { id: "ipswich", leagueId: "premier-league", name: "Ipswich Town", thaiName: "อิปสวิช ทาวน์", shortName: "IPS", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Ipswich_Town.svg/1200px-Ipswich_Town.svg.png", colors: { primary: "#3A64A3", secondary: "#FFFFFF" }, gradient: "from-blue-600 to-white", textGlow: "text-blue-400" },
  { id: "leicester", leagueId: "premier-league", name: "Leicester City", thaiName: "เลสเตอร์ ซิตี้", shortName: "LEI", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/1200px-Leicester_City_crest.svg.png", colors: { primary: "#003090", secondary: "#FDBE11" }, gradient: "from-blue-700 to-yellow-400", textGlow: "text-yellow-400" },
  { id: "southampton", leagueId: "premier-league", name: "Southampton", thaiName: "เซาแธมป์ตัน", shortName: "SOU", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/FC_Southampton.svg/1200px-FC_Southampton.svg.png", colors: { primary: "#D71920", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },

  // La Liga (20)
  { id: "real-madrid", leagueId: "laliga", name: "Real Madrid", thaiName: "เรอัล มาดริด", shortName: "RMA", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/1200px-Real_Madrid_CF.svg.png", colors: { primary: "#FFFFFF", secondary: "#FEBE10" }, gradient: "from-yellow-400 to-yellow-600", textGlow: "text-yellow-400" },
  { id: "barcelona", leagueId: "laliga", name: "Barcelona", thaiName: "บาร์เซโลน่า", shortName: "BAR", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/1200px-FC_Barcelona_%28crest%29.svg.png", colors: { primary: "#A50044", secondary: "#004D98" }, gradient: "from-blue-600 to-red-600", textGlow: "text-blue-400" },
  { id: "atletico-madrid", leagueId: "laliga", name: "Atletico Madrid", thaiName: "แอตเลติโก มาดริด", shortName: "ATM", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Atletico_Madrid_2017_logo.svg/1200px-Atletico_Madrid_2017_logo.svg.png", colors: { primary: "#CB3524", secondary: "#1E3C8A" }, gradient: "from-red-600 to-blue-700", textGlow: "text-red-500" },
  { id: "sevilla", leagueId: "laliga", name: "Sevilla", thaiName: "เซบีย่า", shortName: "SEV", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Sevilla_FC_logo.svg/1200px-Sevilla_FC_logo.svg.png", colors: { primary: "#FFFFFF", secondary: "#ED1C24" }, gradient: "from-white to-red-600", textGlow: "text-white" },
  { id: "real-sociedad", leagueId: "laliga", name: "Real Sociedad", thaiName: "เรอัล โซเซียดาด", shortName: "RSO", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Real_Sociedad_logo.svg/1200px-Real_Sociedad_logo.svg.png", colors: { primary: "#0067B1", secondary: "#FFFFFF" }, gradient: "from-blue-600 to-white", textGlow: "text-blue-400" },
  { id: "villarreal", leagueId: "laliga", name: "Villarreal", thaiName: "บียาร์เรอัล", shortName: "VIL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Villarreal_CF_logo.svg/1200px-Villarreal_CF_logo.svg.png", colors: { primary: "#FFE667", secondary: "#005187" }, gradient: "from-yellow-300 to-blue-700", textGlow: "text-yellow-400" },
  { id: "real-betis", leagueId: "laliga", name: "Real Betis", thaiName: "เรอัล เบติส", shortName: "BET", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_Betis_logo.svg/1200px-Real_Betis_logo.svg.png", colors: { primary: "#00954C", secondary: "#FFFFFF" }, gradient: "from-green-500 to-white", textGlow: "text-green-400" },
  { id: "athletic-bilbao", leagueId: "laliga", name: "Athletic Bilbao", thaiName: "แอธเลติก บิลเบา", shortName: "ATH", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Club_Athletic_Bilbao_logo.svg/1200px-Club_Athletic_Bilbao_logo.svg.png", colors: { primary: "#EE2523", secondary: "#FFFFFF" }, gradient: "from-red-500 to-white", textGlow: "text-red-400" },
  { id: "valencia", leagueId: "laliga", name: "Valencia", thaiName: "บาเลนเซีย", shortName: "VAL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Valenciacf.svg/1200px-Valenciacf.svg.png", colors: { primary: "#FFFFFF", secondary: "#000000" }, gradient: "from-orange-400 to-black", textGlow: "text-orange-400" },
  { id: "celta-vigo", leagueId: "laliga", name: "Celta de Vigo", thaiName: "เซลต้า บีโก้", shortName: "CEL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/RC_Celta_de_Vigo_logo.svg/1200px-RC_Celta_de_Vigo_logo.svg.png", colors: { primary: "#7B1F3E", secondary: "#A5D8F1" }, gradient: "from-red-800 to-blue-300", textGlow: "text-blue-300" },
  { id: "getafe", leagueId: "laliga", name: "Getafe", thaiName: "เฮตาเฟ่", shortName: "GET", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Getafe_CF.svg/1200px-Getafe_CF.svg.png", colors: { primary: "#005999", secondary: "#E82B2B" }, gradient: "from-blue-700 to-red-500", textGlow: "text-blue-400" },
  { id: "osasuna", leagueId: "laliga", name: "Osasuna", thaiName: "โอซาซูน่า", shortName: "OSA", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/03/CA_Osasuna_logo.svg/1200px-CA_Osasuna_logo.svg.png", colors: { primary: "#D91A21", secondary: "#0A346F" }, gradient: "from-red-600 to-blue-800", textGlow: "text-red-400" },
  { id: "espanyol", leagueId: "laliga", name: "Espanyol", thaiName: "เอสปันญ่อล", shortName: "ESP", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/79/RCD_Espanyol_logo.svg/1200px-RCD_Espanyol_logo.svg.png", colors: { primary: "#FFFFFF", secondary: "#007FC8" }, gradient: "from-white to-blue-500", textGlow: "text-white" },
  { id: "rayo-vallecano", leagueId: "laliga", name: "Rayo Vallecano", thaiName: "ราโย บาเยกาโน่", shortName: "RAY", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Rayo_Vallecano_logo.svg/1200px-Rayo_Vallecano_logo.svg.png", colors: { primary: "#FFFFFF", secondary: "#E31717" }, gradient: "from-white to-red-600", textGlow: "text-white" },
  { id: "las-palmas", leagueId: "laliga", name: "Las Palmas", thaiName: "ลัส ปัลมัส", shortName: "LPA", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/UD_Las_Palmas_logo.svg/1200px-UD_Las_Palmas_logo.svg.png", colors: { primary: "#FFCC00", secondary: "#00529C" }, gradient: "from-yellow-400 to-blue-600", textGlow: "text-yellow-400" },
  { id: "leganes", leagueId: "laliga", name: "Leganes", thaiName: "เลกาเนส", shortName: "LEG", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/CD_Legan%C3%A9s_logo.svg/1200px-CD_Legan%C3%A9s_logo.svg.png", colors: { primary: "#00529C", secondary: "#FFFFFF" }, gradient: "from-blue-700 to-white", textGlow: "text-blue-400" },
  { id: "mallorca", leagueId: "laliga", name: "Mallorca", thaiName: "มายอร์ก้า", shortName: "MLL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/RCD_Mallorca_logo.svg/1200px-RCD_Mallorca_logo.svg.png", colors: { primary: "#ED1B24", secondary: "#000000" }, gradient: "from-red-600 to-black", textGlow: "text-red-400" },
  { id: "alaves", leagueId: "laliga", name: "Alaves", thaiName: "อลาเบส", shortName: "ALA", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/26/Deportivo_Alaves_logo.svg/1200px-Deportivo_Alaves_logo.svg.png", colors: { primary: "#0761AF", secondary: "#FFFFFF" }, gradient: "from-blue-700 to-white", textGlow: "text-blue-400" },
  { id: "girona", leagueId: "laliga", name: "Girona", thaiName: "จีโรน่า", shortName: "GIR", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Girona_FC.svg/1200px-Girona_FC.svg.png", colors: { primary: "#CD2534", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "valladolid", leagueId: "laliga", name: "Real Valladolid", thaiName: "บายาโดลิด", shortName: "VLL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/Real_Valladolid_Logo.svg/1200px-Real_Valladolid_Logo.svg.png", colors: { primary: "#6A0DAD", secondary: "#FFFFFF" }, gradient: "from-purple-600 to-white", textGlow: "text-purple-400" },

  // Serie A (20)
  { id: "juventus", leagueId: "serie-a", name: "Juventus", thaiName: "ยูเวนตุส", shortName: "JUV", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Juventus_FC_2017_logo.svg/1200px-Juventus_FC_2017_logo.svg.png", colors: { primary: "#FFFFFF", secondary: "#000000" }, gradient: "from-gray-100 to-black", textGlow: "text-white" },
  { id: "ac-milan", leagueId: "serie-a", name: "AC Milan", thaiName: "เอซี มิลาน", shortName: "MIL", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/AC_Milan_logo.svg/1200px-AC_Milan_logo.svg.png", colors: { primary: "#FB090B", secondary: "#000000" }, gradient: "from-red-600 to-black", textGlow: "text-red-500" },
  { id: "inter-milan", leagueId: "serie-a", name: "Inter Milan", thaiName: "อินเตอร์ มิลาน", shortName: "INT", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/1200px-FC_Internazionale_Milano_2021.svg.png", colors: { primary: "#010E80", secondary: "#000000" }, gradient: "from-blue-800 to-black", textGlow: "text-blue-400" },
  { id: "napoli", leagueId: "serie-a", name: "Napoli", thaiName: "นาโปลี", shortName: "NAP", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/SSC_Napoli_-_Logo_%282020%29.svg/1200px-SSC_Napoli_-_Logo_%282020%29.svg.png", colors: { primary: "#12A0D7", secondary: "#FFFFFF" }, gradient: "from-blue-400 to-white", textGlow: "text-blue-300" },
  { id: "roma", leagueId: "serie-a", name: "AS Roma", thaiName: "โรม่า", shortName: "ROM", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/AS_Roma_logo_%282017%29.svg/1200px-AS_Roma_logo_%282017%29.svg.png", colors: { primary: "#8E1F2F", secondary: "#F0BC42" }, gradient: "from-red-800 to-yellow-400", textGlow: "text-yellow-400" },
  { id: "lazio", leagueId: "serie-a", name: "Lazio", thaiName: "ลาซิโอ", shortName: "LAZ", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/SS_Lazio.svg/1200px-SS_Lazio.svg.png", colors: { primary: "#6DADE4", secondary: "#FFFFFF" }, gradient: "from-blue-400 to-white", textGlow: "text-blue-300" },
  { id: "atalanta", leagueId: "serie-a", name: "Atalanta", thaiName: "อตาลันต้า", shortName: "ATA", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/66/AtalantaBC.svg/1200px-AtalantaBC.svg.png", colors: { primary: "#1E71B8", secondary: "#000000" }, gradient: "from-blue-600 to-black", textGlow: "text-blue-400" },
  { id: "fiorentina", leagueId: "serie-a", name: "Fiorentina", thaiName: "ฟิออเรนติน่า", shortName: "FIO", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/65/ACF_Fiorentina.svg/1200px-ACF_Fiorentina.svg.png", colors: { primary: "#482E92", secondary: "#FFFFFF" }, gradient: "from-purple-700 to-white", textGlow: "text-purple-400" },
  { id: "bologna", leagueId: "serie-a", name: "Bologna", thaiName: "โบโลญญ่า", shortName: "BOL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5b/Bologna_F.C._1909_logo.svg/1200px-Bologna_F.C._1909_logo.svg.png", colors: { primary: "#A21C26", secondary: "#1A3155" }, gradient: "from-red-700 to-blue-800", textGlow: "text-red-400" },
  { id: "torino", leagueId: "serie-a", name: "Torino", thaiName: "โตริโน่", shortName: "TOR", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Torino_FC_Logo.svg/1200px-Torino_FC_Logo.svg.png", colors: { primary: "#8A1E03", secondary: "#FFFFFF" }, gradient: "from-red-800 to-white", textGlow: "text-red-400" },
  { id: "udinese", leagueId: "serie-a", name: "Udinese", thaiName: "อูดิเนเซ่", shortName: "UDI", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/Udinese_Calcio_logo.svg/1200px-Udinese_Calcio_logo.svg.png", colors: { primary: "#000000", secondary: "#FFFFFF" }, gradient: "from-black to-white", textGlow: "text-white" },
  { id: "monza", leagueId: "serie-a", name: "Monza", thaiName: "มอนซ่า", shortName: "MON", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/36/AC_Monza_logo_%282021%29.svg/1200px-AC_Monza_logo_%282021%29.svg.png", colors: { primary: "#E4032E", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "genoa", leagueId: "serie-a", name: "Genoa", thaiName: "เจนัว", shortName: "GEN", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Genoa_CFC.svg/1200px-Genoa_CFC.svg.png", colors: { primary: "#FFFFFF", secondary: "#B22222" }, gradient: "from-white to-red-700", textGlow: "text-white" },
  { id: "sassuolo", leagueId: "serie-a", name: "Sassuolo", thaiName: "ซัสซูโอโล่", shortName: "SAS", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/US_Sassuolo_Calcio_logo.svg/1200px-US_Sassuolo_Calcio_logo.svg.png", colors: { primary: "#007940", secondary: "#000000" }, gradient: "from-green-600 to-black", textGlow: "text-green-400" },
  { id: "empoli", leagueId: "serie-a", name: "Empoli", thaiName: "เอ็มโปลี", shortName: "EMP", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Empoli_FC.svg/1200px-Empoli_FC.svg.png", colors: { primary: "#00519B", secondary: "#FFFFFF" }, gradient: "from-blue-700 to-white", textGlow: "text-blue-400" },
  { id: "salernitana", leagueId: "serie-a", name: "Salernitana", thaiName: "ซาเลอร์นิตาน่า", shortName: "SAL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/US_Salernitana_1919.svg/1200px-US_Salernitana_1919.svg.png", colors: { primary: "#8E1C28", secondary: "#000000" }, gradient: "from-red-800 to-black", textGlow: "text-red-500" },
  { id: "lecce", leagueId: "serie-a", name: "Lecce", thaiName: "เลชเช่", shortName: "LEC", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/54/US_Lecce.svg/1200px-US_Lecce.svg.png", colors: { primary: "#E0202E", secondary: "#F6D531" }, gradient: "from-red-600 to-yellow-400", textGlow: "text-yellow-400" },
  { id: "verona", leagueId: "serie-a", name: "Hellas Verona", thaiName: "เวโรน่า", shortName: "VER", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Hellas_Verona_FC_logo.svg/1200px-Hellas_Verona_FC_logo.svg.png", colors: { primary: "#004F9F", secondary: "#FFDC00" }, gradient: "from-blue-700 to-yellow-400", textGlow: "text-yellow-400" },
  { id: "cagliari", leagueId: "serie-a", name: "Cagliari", thaiName: "คาญารี่", shortName: "CAG", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Cagliari_Calcio_1920.svg/1200px-Cagliari_Calcio_1920.svg.png", colors: { primary: "#B30000", secondary: "#FFFFFF" }, gradient: "from-red-700 to-white", textGlow: "text-red-400" },
  { id: "frosinone", leagueId: "serie-a", name: "Frosinone", thaiName: "โฟรซิโนเน่", shortName: "FRO", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Frosinone_Calcio.svg/1200px-Frosinone_Calcio.svg.png", colors: { primary: "#007FC8", secondary: "#FFDE00" }, gradient: "from-blue-500 to-yellow-400", textGlow: "text-yellow-400" },

  // Bundesliga (18)
  { id: "bayern-munich", leagueId: "bundesliga", name: "Bayern Munich", thaiName: "บาเยิร์น มิวนิค", shortName: "BAY", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/1200px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png", colors: { primary: "#DC052D", secondary: "#FFFFFF" }, gradient: "from-red-600 to-red-800", textGlow: "text-red-500" },
  { id: "borussia-dortmund", leagueId: "bundesliga", name: "Borussia Dortmund", thaiName: "โบรุสเซีย ดอร์ทมุนด์", shortName: "BVB", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/1200px-Borussia_Dortmund_logo.svg.png", colors: { primary: "#FDE100", secondary: "#000000" }, gradient: "from-yellow-400 to-yellow-600", textGlow: "text-yellow-400" },
  { id: "bayer-leverkusen", leagueId: "bundesliga", name: "Bayer Leverkusen", thaiName: "ไบเออร์ เลเวอร์คูเซ่น", shortName: "B04", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Bayer_04_Leverkusen_logo.svg/1200px-Bayer_04_Leverkusen_logo.svg.png", colors: { primary: "#E32219", secondary: "#FFFFFF" }, gradient: "from-red-600 to-black", textGlow: "text-red-400" },
  { id: "rb-leipzig", leagueId: "bundesliga", name: "RB Leipzig", thaiName: "แอร์เบ ไลป์ซิก", shortName: "RBL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/1200px-RB_Leipzig_2014_logo.svg.png", colors: { primary: "#DD0741", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "eintracht-frankfurt", leagueId: "bundesliga", name: "Eintracht Frankfurt", thaiName: "แฟรงค์เฟิร์ต", shortName: "SGE", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eintracht_Frankfurt_Logo.svg/1200px-Eintracht_Frankfurt_Logo.svg.png", colors: { primary: "#E32219", secondary: "#000000" }, gradient: "from-red-600 to-black", textGlow: "text-red-400" },
  { id: "wolfsburg", leagueId: "bundesliga", name: "Wolfsburg", thaiName: "โวล์ฟสบวร์ก", shortName: "WOB", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/VfL_Wolfsburg_Logo.svg/1200px-VfL_Wolfsburg_Logo.svg.png", colors: { primary: "#65FF00", secondary: "#FFFFFF" }, gradient: "from-green-400 to-white", textGlow: "text-green-400" },
  { id: "freiburg", leagueId: "bundesliga", name: "SC Freiburg", thaiName: "ไฟร์บวร์ก", shortName: "SCF", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/SC_Freiburg_logo.svg/1200px-SC_Freiburg_logo.svg.png", colors: { primary: "#E30613", secondary: "#000000" }, gradient: "from-red-600 to-black", textGlow: "text-red-400" },
  { id: "union-berlin", leagueId: "bundesliga", name: "Union Berlin", thaiName: "ยูเนี่ยน เบอร์ลิน", shortName: "FCU", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/1._FC_Union_Berlin_Logo.svg/1200px-1._FC_Union_Berlin_Logo.svg.png", colors: { primary: "#DD0741", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "borussia-mgladbach", leagueId: "bundesliga", name: "Borussia Monchengladbach", thaiName: "กลัดบัค", shortName: "BMG", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Borussia_M%C3%B6nchengladbach_logo.svg/1200px-Borussia_M%C3%B6nchengladbach_logo.svg.png", colors: { primary: "#000000", secondary: "#FFFFFF" }, gradient: "from-black to-white", textGlow: "text-white" },
  { id: "stuttgart", leagueId: "bundesliga", name: "VfB Stuttgart", thaiName: "ชตุ๊ตการ์ท", shortName: "VFB", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/VfB_Stuttgart_1893_Logo.svg/1200px-VfB_Stuttgart_1893_Logo.svg.png", colors: { primary: "#E32219", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "augsburg", leagueId: "bundesliga", name: "FC Augsburg", thaiName: "เอาก์สบวร์ก", shortName: "FCA", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/FC_Augsburg_logo.svg/1200px-FC_Augsburg_logo.svg.png", colors: { primary: "#BA3733", secondary: "#0E4C93" }, gradient: "from-red-700 to-green-600", textGlow: "text-green-400" },
  { id: "werder-bremen", leagueId: "bundesliga", name: "Werder Bremen", thaiName: "เวร์เดอร์ เบรเมน", shortName: "SVW", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/SV-Werder-Bremen-Logo.svg/1200px-SV-Werder-Bremen-Logo.svg.png", colors: { primary: "#1D8564", secondary: "#FFFFFF" }, gradient: "from-green-600 to-white", textGlow: "text-green-400" },
  { id: "hoffenheim", leagueId: "bundesliga", name: "TSG Hoffenheim", thaiName: "ฮอฟเฟ่นไฮม์", shortName: "TSG", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Logo_TSG_1899_Hoffenheim.svg/1200px-Logo_TSG_1899_Hoffenheim.svg.png", colors: { primary: "#1A63B0", secondary: "#FFFFFF" }, gradient: "from-blue-600 to-white", textGlow: "text-blue-400" },
  { id: "heidenheim", leagueId: "bundesliga", name: "Heidenheim", thaiName: "ไฮเดนไฮม์", shortName: "FCH", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/1._FC_Heidenheim_1846.svg/1200px-1._FC_Heidenheim_1846.svg.png", colors: { primary: "#E30613", secondary: "#0064A8" }, gradient: "from-red-600 to-blue-600", textGlow: "text-blue-400" },
  { id: "mainz", leagueId: "bundesliga", name: "Mainz 05", thaiName: "ไมนซ์", shortName: "M05", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/FSV_Mainz_05_Logo.svg/1200px-FSV_Mainz_05_Logo.svg.png", colors: { primary: "#E30613", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "bochum", leagueId: "bundesliga", name: "VfL Bochum", thaiName: "โบคุ่ม", shortName: "BOC", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/VfL_Bochum_logo.svg/1200px-VfL_Bochum_logo.svg.png", colors: { primary: "#00529C", secondary: "#FFFFFF" }, gradient: "from-blue-700 to-white", textGlow: "text-blue-400" },
  { id: "darmstadt", leagueId: "bundesliga", name: "Darmstadt 98", thaiName: "ดาร์มสตัดท์", shortName: "SVD", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/92/SV_Darmstadt_98.svg/1200px-SV_Darmstadt_98.svg.png", colors: { primary: "#0061A8", secondary: "#FFFFFF" }, gradient: "from-blue-600 to-white", textGlow: "text-blue-400" },
  { id: "cologne", leagueId: "bundesliga", name: "FC Cologne", thaiName: "โคโลญ", shortName: "KOE", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/FC_Cologne_logo.svg/1200px-FC_Cologne_logo.svg.png", colors: { primary: "#E32219", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },

  // Ligue 1 (18)
  { id: "psg", leagueId: "ligue-1", name: "Paris Saint-Germain", thaiName: "ปารีส แซงต์-แชร์กแมง", shortName: "PSG", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/1200px-Paris_Saint-Germain_F.C..svg.png", colors: { primary: "#004170", secondary: "#DA291C" }, gradient: "from-blue-800 to-red-500", textGlow: "text-blue-400" },
  { id: "marseille", leagueId: "ligue-1", name: "Olympique de Marseille", thaiName: "โอลิมปิก มาร์กเซย", shortName: "OM", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Olympique_Marseille_logo.svg/1200px-Olympique_Marseille_logo.svg.png", colors: { primary: "#00B9F1", secondary: "#FFFFFF" }, gradient: "from-blue-400 to-white", textGlow: "text-blue-300" },
  { id: "monaco", leagueId: "ligue-1", name: "AS Monaco", thaiName: "โมนาโก", shortName: "ASM", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/AS_Monaco_FC.svg/1200px-AS_Monaco_FC.svg.png", colors: { primary: "#E30613", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "lille", leagueId: "ligue-1", name: "Lille", thaiName: "ลีลล์", shortName: "LOSC", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Lille_OSC_2018_logo.svg/1200px-Lille_OSC_2018_logo.svg.png", colors: { primary: "#E30613", secondary: "#1E3A8A" }, gradient: "from-red-600 to-blue-800", textGlow: "text-red-400" },
  { id: "lyon", leagueId: "ligue-1", name: "Olympique Lyonnais", thaiName: "ลียง", shortName: "OL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Olympique_Lyonnais.svg/1200px-Olympique_Lyonnais.svg.png", colors: { primary: "#FFFFFF", secondary: "#E30613" }, gradient: "from-red-600 to-blue-500", textGlow: "text-white" },
  { id: "rennes", leagueId: "ligue-1", name: "Rennes", thaiName: "แรนส์", shortName: "SRFC", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Stade_Rennais_FC.svg/1200px-Stade_Rennais_FC.svg.png", colors: { primary: "#E30613", secondary: "#000000" }, gradient: "from-red-600 to-black", textGlow: "text-red-400" },
  { id: "nice", leagueId: "ligue-1", name: "OGC Nice", thaiName: "นีซ", shortName: "OGC", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/24/OGC_Nice_logo.svg/1200px-OGC_Nice_logo.svg.png", colors: { primary: "#000000", secondary: "#E30613" }, gradient: "from-black to-red-600", textGlow: "text-red-400" },
  { id: "reims", leagueId: "ligue-1", name: "Reims", thaiName: "แร็งส์", shortName: "SDR", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Stade_de_Reims_logo.svg/1200px-Stade_de_Reims_logo.svg.png", colors: { primary: "#E30613", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "lens", leagueId: "ligue-1", name: "Lens", thaiName: "ล็องส์", shortName: "RCL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/RC_Lens_logo.svg/1200px-RC_Lens_logo.svg.png", colors: { primary: "#FDE100", secondary: "#E30613" }, gradient: "from-yellow-400 to-red-600", textGlow: "text-yellow-400" },
  { id: "montpellier", leagueId: "ligue-1", name: "Montpellier", thaiName: "มงเปลลิเยร์", shortName: "MHSC", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Montpellier_HSC_logo.svg/1200px-Montpellier_HSC_logo.svg.png", colors: { primary: "#E30613", secondary: "#000000" }, gradient: "from-blue-700 to-orange-400", textGlow: "text-orange-400" },
  { id: "strasbourg", leagueId: "ligue-1", name: "Strasbourg", thaiName: "สตราสบูร์ก", shortName: "RCSA", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/RC_Strasbourg_Alsace_logo.svg/1200px-RC_Strasbourg_Alsace_logo.svg.png", colors: { primary: "#00A9E0", secondary: "#FFFFFF" }, gradient: "from-blue-400 to-white", textGlow: "text-blue-300" },
  { id: "nantes", leagueId: "ligue-1", name: "Nantes", thaiName: "น็องต์", shortName: "FCN", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/FC_Nantes_2019_logo.svg/1200px-FC_Nantes_2019_logo.svg.png", colors: { primary: "#FDE100", secondary: "#006747" }, gradient: "from-yellow-400 to-green-600", textGlow: "text-yellow-400" },
  { id: "toulouse", leagueId: "ligue-1", name: "Toulouse", thaiName: "ตูลูส", shortName: "TFC", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Toulouse_FC.svg/1200px-Toulouse_FC.svg.png", colors: { primary: "#5F249F", secondary: "#FFFFFF" }, gradient: "from-purple-700 to-white", textGlow: "text-purple-400" },
  { id: "le-havre", leagueId: "ligue-1", name: "Le Havre", thaiName: "ลอร์อฟร์", shortName: "HAC", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a5/Le_Havre_AC.svg/1200px-Le_Havre_AC.svg.png", colors: { primary: "#00B2E3", secondary: "#FFFFFF" }, gradient: "from-blue-400 to-white", textGlow: "text-blue-300" },
  { id: "brest", leagueId: "ligue-1", name: "Brest", thaiName: "เบรสต์", shortName: "SB29", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Stade_Brestois_29_logo.svg/1200px-Stade_Brestois_29_logo.svg.png", colors: { primary: "#E30613", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "metz", leagueId: "ligue-1", name: "Metz", thaiName: "เม็ซ", shortName: "FCM", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/FC_Metz_logo.svg/1200px-FC_Metz_logo.svg.png", colors: { primary: "#E30613", secondary: "#FFFFFF" }, gradient: "from-red-600 to-white", textGlow: "text-red-400" },
  { id: "lorient", leagueId: "ligue-1", name: "Lorient", thaiName: "ลอริยองต์", shortName: "FCL", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/FC_Lorient_logo.svg/1200px-FC_Lorient_logo.svg.png", colors: { primary: "#E30613", secondary: "#FFFFFF" }, gradient: "from-orange-500 to-white", textGlow: "text-orange-400" },
  { id: "clermont", leagueId: "ligue-1", name: "Clermont", thaiName: "แกร์มง", shortName: "CF63", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Clermont_Foot_logo.svg/1200px-Clermont_Foot_logo.svg.png", colors: { primary: "#E30613", secondary: "#000000" }, gradient: "from-red-600 to-black", textGlow: "text-red-400" }
];

const images = [
  { teamId: "manchester-united", playerName: "บรูโน่ แฟร์นันด์ส", urls: { thumbnail: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400&h=600&fit=crop", preview: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&h=1200&fit=crop", full: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1200&h=1800&fit=crop" }, type: "cutout", tags: ["กองกลาง", "กัปตัน", "ดีใจ"], dimensions: { width: 1200, height: 1800 }, downloadCount: 0 },
  { teamId: "manchester-united", playerName: "มาร์คัส แรชฟอร์ด", urls: { thumbnail: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=400&h=600&fit=crop", preview: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&h=1200&fit=crop", full: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=1200&h=1800&fit=crop" }, type: "cutout", tags: ["กองหน้า", "ยิงประตู", "วิ่ง"], dimensions: { width: 1200, height: 1800 }, downloadCount: 0 },
  { teamId: "manchester-united", playerName: "อเลฮานโดร การ์นาโช่", urls: { thumbnail: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=400&h=600&fit=crop", preview: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&h=1200&fit=crop", full: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=1200&h=1800&fit=crop" }, type: "cutout", tags: ["กองหน้า", "แอ็คชั่น", "ปีก"], dimensions: { width: 1200, height: 1800 }, downloadCount: 0 },
  { teamId: "liverpool", playerName: "โมฮาเหม็ด ซาลาห์", urls: { thumbnail: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=600&fit=crop", preview: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=1200&fit=crop", full: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=1800&fit=crop" }, type: "cutout", tags: ["กองหน้า", "ยิงประตู", "ดีใจ"], dimensions: { width: 1200, height: 1800 }, downloadCount: 0 },
  { teamId: "liverpool", playerName: "เวอร์จิล ฟาน ไดจ์ค", urls: { thumbnail: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=400&h=600&fit=crop", preview: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&h=1200&fit=crop", full: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=1200&h=1800&fit=crop" }, type: "cutout", tags: ["กองหลัง", "กัปตัน", "สไลด์"], dimensions: { width: 1200, height: 1800 }, downloadCount: 0 }
];

async function seedFirestore() {
  console.log('เริ่มอัปโหลดข้อมูลครบทุกลีก (96 ทีม) ไปยัง Firestore...\n');
  try {
    // ลบข้อมูลเก่าก่อน
    console.log('🗑️ กำลังลบข้อมูลเก่า...');
    const collections = ['leagues', 'teams', 'images'];
    for (const coll of collections) {
      const snapshot = await db.collection(coll).get();
      const batch = db.batch();
      snapshot.docs.forEach(doc => batch.delete(doc.ref));
      await batch.commit();
    }
    console.log('✓ ลบข้อมูลเก่าแล้ว\n');

    // อัปโหลด leagues (5 ลีก)
    console.log('📁 กำลังอัปโหลด 5 ลีก...');
    for (const league of leagues) {
      await db.collection('leagues').doc(league.id).set({ ...league, createdAt: admin.firestore.FieldValue.serverTimestamp() });
      console.log(`  ✓ ${league.thaiName}`);
    }

    // อัปโหลด teams (96 ทีม)
    console.log(`\n📁 กำลังอัปโหลด ${teams.length} ทีม...`);
    let count = 0;
    for (const team of teams) {
      await db.collection('teams').doc(team.id).set({ ...team, createdAt: admin.firestore.FieldValue.serverTimestamp() });
      count++;
      if (count % 20 === 0) console.log(`  ✓ ${count}/${teams.length} ทีม`);
    }
    console.log(`  ✓ ครบ ${count} ทีม`);

    // อัปโหลด images
    console.log('\n📁 กำลังอัปโหลดรูปภาพตัวอย่าง...');
    for (const image of images) {
      await db.collection('images').add({ ...image, createdAt: admin.firestore.FieldValue.serverTimestamp() });
    }
    console.log(`  ✓ ${images.length} รูป`);

    console.log('\n✅ เสร็จสิ้น!');
    console.log(`📊 สรุป: ${leagues.length} ลีก, ${teams.length} ทีม, ${images.length} รูป`);
    console.log('\nลีกที่มี:');
    leagues.forEach(l => console.log(`  • ${l.thaiName} (${teams.filter(t => t.leagueId === l.id).length} ทีม)`));

  } catch (error) {
    console.error('\n❌ เกิดข้อผิดพลาด:', error);
  } finally {
    process.exit(0);
  }
}

seedFirestore();
